---
version: "2"
linters:
  default: all
  disable:
    - wsl
    - varnamelen
    - canonicalheader
    - cyclop
    - depguard
    - err113
    - errcheck
    - exhaustive
    - exhaustruct
    - funlen
    - gochecknoglobals
    - goconst
    - gosec
    - inamedparam
    - lll
    - mnd
    - nlreturn
    - nonamedreturns
    - paralleltest
    - revive
    - staticcheck
    - tagliatelle
    - thelper
    - wrapcheck
    - ireturn
